[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
extend-exclude = '''
/migrations/
'''

[tool.isort]
profile = "black"
combine_as_imports = true
include_trailing_comma = true
line_length = 88
skip = [
    "core/migrations"
]
